//! Local error type.
//!
//! Replaces `daruma_shared::CoreError` so the skeleton is
//! dependency-free. the host maps [`ActionsError`] onto its own error surface
//! when wiring the layer. The shape is generated by layer-kit's shared
//! `layer_error!` macro instead of hand-copied per layer.

layer_kit::layer_error!(ActionsError {
    Ai(ai, "AI provider failed or returned an unusable response."),
    Validation(validation, "Output failed validation (missing or invalid fields)."),
    Serde(serde, "(De)serialization failure."),
});

impl From<crate::ai::AiError> for ActionsError {
    fn from(value: crate::ai::AiError) -> Self {
        Self::ai(value.to_string())
    }
}
